#!/usr/bin/python -B

import os

from gi.repository import Gdk
from gi.repository import GLib
from gi.repository import Gtk

from king_phisher.client import client

def main():
	os.environ['GLADE_FILE'] = 'king_phisher/KingPhisherClient.glade'
	GLib.threads_init()
	Gdk.threads_init()
	main_window = client.KingPhisherClient()
	main_window.show_all()
	if main_window.server_connect():
		Gtk.main()
	main_window.save_config()

if __name__ == '__main__':
	main()
